### PR TITLE
drop dask-kubernetes

### LINKED ISSUE #26: drop dask-kubernetes
@jhamman @TomAugspurger Pangeo jupyterhubs and binderhubs are now all using dask-gateway:
https://github.com/pangeo-data/pangeo-cloud-federation
https://github.com/pangeo-data/pangeo-binder

So I think we can drop dask-kubernetes, correct? 
https://github.com/conda-forge/pangeo-dask-feedstock/blob/80f8673f33d0908f634f8e35c3fa2ff2baf9366f/recipe/meta.yaml#L15

related https://github.com/pangeo-data/pangeo-docker-images/issues/94

### PR DESCRIPTION
**Pull request by scottyhq**
Fixes #26 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by scottyhq** [comment]
@conda-forge-admin, please rerender

**Comment by TomAugspurger** [comment]
@scottyhq can the action watching dask-kubernetes be removed? https://github.com/conda-forge/pangeo-dask-feedstock/blob/1571f0ce17e7db0eb3e7739779f67483935ee584/.github/workflows/watch-conda-forge.yml#L60-L73

**Comment by scottyhq** [comment]
good point. we'll also probably have to tackle https://github.com/conda-forge/pangeo-dask-feedstock/issues/16 or pangeo-bot will try to put it back in!

**Comment by scottyhq** [comment]
closed in favor of #84

**Pull request closed without merging**
