### PR TITLE
Bump dask-gateway version

### PR DESCRIPTION
**Pull request by yuvipanda**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by yuvipanda** [comment]
@conda-forge-admin, please rerender

**Review by jhamman — APPROVED** [review]

**Comment by yuvipanda** [comment]
@jhamman think you can hit merge too? :D

**Comment by scottyhq** [comment]
The bot dispatcher needs to be reset every so often if you want to avoid doing this manually! https://github.com/pangeo-bot/dispatcher/issues/2

**Comment by scottyhq** [comment]
@yuvipanda can I add you as a maintainer for this repo so that you can merge future PRs?

**Comment by yuvipanda** [comment]
@scottyhq yep!

**Pull request merged**
